<a href="https://colab.research.google.com/github/hridhyapr/SMART-FEEDBACK-COLLECTION-PORTAL/blob/main/Sports.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully")

Libraries imported successfully

In [2]:
from google.colab import files

uploaded = files.upload()

Saving sports.csv to sports.csv

In [14]:
df=pd.read_csv('sports.csv')

In [11]:
display(df.head())

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [12]:
display(df.tail())

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [16]:
season = df.copy()
duplicates = season.sample(8, random_state=42)
df = pd.concat([season, duplicates], ignore_index=True)

In [18]:
print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (1111, 20)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [19]:
display(df.head())

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [20]:
display(df.tail())

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1106,829761,2015,Kolkata,2015-05-07,League,PP Chawla,Eden Gardens,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,13.0,172.0,20.0,N,NaN,AK Chaudhary,M Erasmus
1107,980969,2016,Bangalore,2016-05-07,League,V Kohli,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rising Pune Supergiants,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,192.0,20.0,N,NaN,CB Gaffaney,BNJ Oxenford
1108,1254074,2021,Chennai,2021-04-23,League,KL Rahul,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,9.0,132.0,20.0,N,NaN,C Shamshuddin,Nitin Menon
1109,392221,2009,Centurion,2009-05-12,League,LRPL Taylor,SuperSport Park,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,6.0,174.0,20.0,N,NaN,M Erasmus,SS Hazare
1110,548350,2012,Bangalore,2012-05-02,League,Azhar Mahmood,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,4.0,159.0,20.0,N,NaN,BF Bowden,C Shamshuddin

In [21]:
display(df.sample(5, random_state=42))

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
436,734007,2014,Hyderabad,2014-05-14,League,WP Saha,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,6.0,206.0,20.0,N,NaN,VA Kulkarni,PG Pathak
539,980945,2016,Delhi,2016-04-27,League,CH Morris,Feroz Shah Kotla,Delhi Daredevils,Gujarat Lions,Delhi Daredevils,field,Gujarat Lions,runs,1.0,173.0,20.0,N,NaN,M Erasmus,S Ravi
56,336039,2007/08,Mumbai,2008-05-31,Semi Final,M Ntini,Wankhede Stadium,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,bat,Chennai Super Kings,wickets,9.0,113.0,20.0,N,NaN,Asad Rauf,DJ Harper
695,1136620,2018,Mumbai,2018-05-27,Final,SR Watson,Wankhede Stadium,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,8.0,179.0,20.0,N,NaN,M Erasmus,S Ravi
722,1178402,2019,Mumbai,2019-04-13,League,JC Buttler,Wankhede Stadium,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,188.0,20.0,N,NaN,A Nand Kishore,Nitin Menon

In [22]:
rows, columns = df.shape

print("Rows    :", rows)
print("Columns :", columns)

Rows    : 1111
Columns : 20

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1111 entries, 0 to 1110
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1111 non-null   int64
 1   season           1111 non-null   object
 2   city             1060 non-null   object
 3   date             1111 non-null   object
 4   match_type       1111 non-null   object
 5   player_of_match  1106 non-null   object
 6   venue            1111 non-null   object
 7   team1            1111 non-null   object
 8   team2            1111 non-null   object
 9   toss_winner      1111 non-null   object
 10  toss_decision    1111 non-null   object
 11  winner           1106 non-null   object
 12  result           1111 non-null   object
 13  result_margin    1092 non-null   float64
 14  target_runs      1108 non-null   float64
 15  target_overs     1108 non-null   float64
 16  super_over       1111 non-null   object
 17  method           21 non-null     object
 18  umpire1          1111 non-null   object
 19  umpire2          1111 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 173.7+ KB

In [24]:
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
id,1111.0,NaN,NaN,NaN,904428.362736,367872.016253,335982.0,548332.5,980959.0,1254063.5,1426312.0
season,1111,17,2012,77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,1060,36,Mumbai,175,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date,1111,823,2016-05-07,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
match_type,1111,8,League,1045,NaN,NaN,NaN,NaN,NaN,NaN,NaN
player_of_match,1106,291,AB de Villiers,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
venue,1111,58,Eden Gardens,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
team1,1111,19,Royal Challengers Bangalore,139,NaN,NaN,NaN,NaN,NaN,NaN,NaN
team2,1111,19,Mumbai Indians,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN
toss_winner,1111,19,Mumbai Indians,144,NaN,NaN,NaN,NaN,NaN,NaN,NaN
toss_decision,1111,2,field,717,NaN,NaN,NaN,NaN,NaN,NaN,NaN
winner,1106,19,Mumbai Indians,145,NaN,NaN,NaN,NaN,NaN,NaN,NaN
result,1111,4,wickets,588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
result_margin,1092.0,NaN,NaN,NaN,17.194139,21.675484,1.0,6.0,8.0,20.0,146.0
target_runs,1108.0,NaN,NaN,NaN,165.573105,33.362495,43.0,146.0,166.0,187.0,288.0
target_overs,1108.0,NaN,NaN,NaN,19.762816,1.569903,5.0,20.0,20.0,20.0,20.0
super_over,1111,2,N,1097,NaN,NaN,NaN,NaN,NaN,NaN,NaN
method,21,1,D/L,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
umpire1,1111,62,AK Chaudhary,117,NaN,NaN,NaN,NaN,NaN,NaN,NaN
umpire2,1111,62,S Ravi,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
missing = (
    df.isnull()
      .sum()
      .to_frame("missing_count")
)

missing["missing_percent"] = (
    missing["missing_count"] / len(df) * 100
).round(2)

display(
    missing.sort_values(
        "missing_percent",
        ascending=False
    )
)

                 missing_count  missing_percent
method                    1090            98.11
city                        51             4.59
result_margin               19             1.71
player_of_match              5             0.45
winner                       5             0.45
target_runs                  3             0.27
target_overs                 3             0.27
id                           0             0.00
date                         0             0.00
season                       0             0.00
venue                        0             0.00
match_type                   0             0.00
toss_decision                0             0.00
toss_winner                  0             0.00
team2                        0             0.00
team1                        0             0.00
result                       0             0.00
super_over                   0             0.00
umpire1                      0             0.00
umpire2                      0             0.00

In [26]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 16

In [27]:
categorical_columns = [
    "season",
    "id",
    "city",
    "date"
]

for column in categorical_columns:
    print(f"\n--- {column.upper()} ---")
    print(df[column].value_counts(dropna=False))

--- SEASON ---
season
2012       77
2013       77
2023       75
2022       74
2011       73
2024       73
2021       62
2016       62
2009/10    61
2018       60
2020/21    60
2014       60
2015       60
2017       60
2019       60
2009       59
2007/08    58
Name: count, dtype: int64

--- ID ---
id
1082616    2
392213     2
1254074    2
548369     2
1254083    2
          ..
598040     1
598039     1
598038     1
598037     1
598046     1
Name: count, Length: 1095, dtype: int64

--- CITY ---
city
Mumbai            175
Kolkata            94
Delhi              92
Chennai            87
Hyderabad          78
Bangalore          67
Chandigarh         61
Jaipur             57
Pune               51
NaN                51
Abu Dhabi          37
Ahmedabad          37
Bengaluru          30
Durban             15
Visakhapatnam      15
Lucknow            14
Centurion          14
Dharamsala         13
Dubai              13
Rajkot             11
Sharjah            10
Indore              9
Navi Mumbai         9
Johannesburg        8
Ranchi              8
Port Elizabeth      7
Cuttack             7
Cape Town           7
Raipur              6
Kochi               5
Mohali              5
Kanpur              4
East London         3
Kimberley           3
Nagpur              3
Guwahati            3
Bloemfontein        2
Name: count, dtype: int64

--- DATE ---
date
2016-05-07    3
2010-03-28    3
2016-04-23    3
2017-04-23    3
2009-05-12    3
             ..
2024-05-09    1
2024-05-08    1
2024-05-07    1
2024-05-06    1
2024-05-04    1
Name: count, Length: 823, dtype: int64

In [28]:
score_columns_raw = [
    "method",
    "result_margin",
    "player_of_match",
    "umpire1",
    "umpire2",
    "venue",
    "team1",
    "team2",
    "toss_winner",
    "toss_decision",
    "winner",
    "win_by_runs", # This column is not in df.info()
    "win_by_wickets", # This column is not in df.info()
    "player_of_match_score" # This column is not in df.info()
]

# Filter out columns that do not exist in the DataFrame
existing_score_columns = [col for col in score_columns_raw if col in df.columns]

print("--- Numeric Score Columns (Min/Max) ---")
for column in existing_score_columns:
    if pd.api.types.is_numeric_dtype(df[column]):
        print(
            f"{column}: "
            f"min={df[column].min()}, "
            f"max={df[column].max()}"
        )

print("\n--- Categorical Score Columns (Value Counts) ---")
for column in existing_score_columns:
    if pd.api.types.is_object_dtype(df[column]):
        print(f"\n--- {column.upper()} ---")
        # Use value_counts to inspect categorical data, including NaNs
        print(df[column].value_counts(dropna=False))

--- Numeric Score Columns (Min/Max) ---
result_margin: min=1.0, max=146.0

--- Categorical Score Columns (Value Counts) ---

--- METHOD ---
method
NaN    1090
D/L      21
Name: count, dtype: int64

--- PLAYER_OF_MATCH ---
player_of_match
AB de Villiers     25
CH Gayle           22
RG Sharma          19
V Kohli            19
DA Warner          18
                   ..
A Manohar           1
J Fraser-McGurk     1
WG Jacks            1
Simarjeet Singh     1
Shahbaz Ahmed       1
Name: count, Length: 292, dtype: int64

--- UMPIRE1 ---
umpire1
AK Chaudhary             117
HDPK Dharmasena           80
KN Ananthapadmanabhan     60
CB Gaffaney               54
Asad Rauf                 51
S Ravi                    50
Nitin Menon               50
M Erasmus                 43
BF Bowden                 38
Aleem Dar                 38
BNJ Oxenford              36
BR Doctrove               34
AY Dandekar               30
C Shamshuddin             29
A Nand Kishore            24
RE Koertzen               20
J Madanagopal             20
S Asnani                  19
NJ Llong                  18
CK Nandan                 16
JD Cloete                 16
RK Illingworth            14
VA Kulkarni               13
BG Jerling                13
A Totre                   13
K Hariharan               11
S Das                     11
SS Hazare                 11
R Pandit                  10
MR Benson                 10
Navdeep Singh              9
DJ Harper                  9
RJ Tucker                  9
MA Gough                   9
A Deshmukh                 9
HAS Khalid                 8
RM Deshpande               7
PR Reiffel                 7
IL Howell                  7
PG Pathak                  7
GAV Baxter                 7
YC Barde                   6
Chirra Ravikanthreddy      6
SJ Davis                   6
SK Tarapore                5
SD Fry                     5
NA Patwardhan              5
MV Saidharshan Kumar       4
IJ Gould                   4
AM Saheba                  4
UV Gandhe                  4
VK Sharma                  4
Vinod Seshan               3
K Bharatan                 3
GR Sadashiv Iyer           3
K Srinath                  2
AV Jayaprakash             2
K Srinivasan               2
Tapan Sharma               2
AG Wharf                   2
SL Shastri                 1
SJA Taufel                 1
Name: count, dtype: int64

--- UMPIRE2 ---
umpire2
S Ravi                   83
C Shamshuddin            63
VK Sharma                62
Nitin Menon              55
SJA Taufel               54
RJ Tucker                53
VA Kulkarni              44
CK Nandan                43
YC Barde                 38
RB Tiffin                30
BNJ Oxenford             30
M Erasmus                27
UV Gandhe                27
SK Tarapore              26
RK Illingworth           25
CB Gaffaney              24
AM Saheba                22
PR Reiffel               21
RE Koertzen              21
NJ Llong                 20
HDPK Dharmasena          19
DJ Harper                19
Tapan Sharma             18
AK Chaudhary             16
NA Patwardhan            15
K Srinath                14
R Pandit                 14
KN Ananthapadmanabhan    13
A Nand Kishore           13
SL Shastri               13
MA Gough                 12
MV Saidharshan Kumar     12
K Hariharan              12
Vinod Seshan             11
S Asnani                 11
HAS Khalid               10
Navdeep Singh            10
PG Pathak                 9
GR Sadashiv Iyer          9
BR Doctrove               8
SS Hazare                 7
IL Howell                 7
K Srinivasan              7
AL Hill                   6
GA Pratapkumar            6
I Shivram                 6
N Pandit                  6
J Madanagopal             6
S Das                     5
TH Wijewardene            5
BG Jerling                4
AV Jayaprakash            4
A Deshmukh                3
MR Benson                 2
AY Dandekar               2
IJ Gould                  2
SD Ranade                 2
SJ Davis                  1
JD Cloete                 1
BF Bowden                 1
SD Fry                    1
Subroto Das               1
Name: count, dtype: int64

--- VENUE ---
venue
Eden Gardens                                                             78
Wankhede Stadium                                                         73
M Chinnaswamy Stadium                                                    67
Feroz Shah Kotla                                                         62
MA Chidambaram Stadium, Chepauk                                          49
Rajiv Gandhi International Stadium, Uppal                                49
Sawai Mansingh Stadium                                                   47
Dubai International Cricket Stadium                                      46
Wankhede Stadium, Mumbai                                                 46
Punjab Cricket Association Stadium, Mohali                               35
Sheikh Zayed Stadium                                                     29
MA Chidambaram Stadium, Chepauk, Chennai                                 29
Sharjah Cricket Stadium                                                  28
Narendra Modi Stadium, Ahmedabad                                         25
Maharashtra Cricket Association Stadium                                  22
Dr DY Patil Sports Academy, Mumbai                                       20
Dr DY Patil Sports Academy                                               18
Brabourne Stadium, Mumbai                                                17
Subrata Roy Sahara Stadium                                               16
Eden Gardens, Kolkata                                                    16
Arun Jaitley Stadium, Delhi                                              16
Kingsmead                                                                15
M Chinnaswamy Stadium, Bengaluru                                         15
M.Chinnaswamy Stadium                                                    15
Rajiv Gandhi International Stadium                                       15
SuperSport Park                                                          14
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     14
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    14
Arun Jaitley Stadium                                                     14
Maharashtra Cricket Association Stadium, Pune                            13
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                      13
Sardar Patel Stadium, Motera                                             12
Saurashtra Cricket Association Stadium                                   11
Punjab Cricket Association IS Bindra Stadium, Mohali                     11
Punjab Cricket Association IS Bindra Stadium                             10
Sawai Mansingh Stadium, Jaipur                                           10
Brabourne Stadium                                                        10
Himachal Pradesh Cricket Association Stadium                              9
MA Chidambaram Stadium                                                    9
Holkar Cricket Stadium                                                    9
New Wanderers Stadium                                                     8
JSCA International Stadium Complex                                        8
Zayed Cricket Stadium, Abu Dhabi                                          8
St George's Park                                                          7
Barabati Stadium                                                          7
Newlands                                                                  7
Shaheed Veer Narayan Singh International Stadium                          6
Nehru Stadium                                                             5
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur        5
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh          5
Green Park                                                                4
Himachal Pradesh Cricket Association Stadium, Dharamsala                  4
De Beers Diamond Oval                                                     3
Buffalo Park                                                              3
Barsapara Cricket Stadium, Guwahati                                       3
Vidarbha Cricket Association Stadium, Jamtha                              3
OUTsurance Oval                                                           2
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam        2
Name: count, dtype: int64

--- TEAM1 ---
team1
Royal Challengers Bangalore    139
Chennai Super Kings            130
Mumbai Indians                 125
Kolkata Knight Riders          124
Rajasthan Royals               101
Kings XI Punjab                 92
Delhi Daredevils                87
Sunrisers Hyderabad             86
Delhi Capitals                  41
Deccan Chargers                 40
Punjab Kings                    32
Lucknow Super Giants            23
Pune Warriors                   23
Gujarat Titans                  21
Gujarat Lions                   17
Royal Challengers Bengaluru      9
Kochi Tuskers Kerala             7
Rising Pune Supergiant           7
Rising Pune Supergiants          7
Name: count, dtype: int64

--- TEAM2 ---
team2
Mumbai Indians                 140
Kolkata Knight Riders          132
Rajasthan Royals               122
Chennai Super Kings            110
Royal Challengers Bangalore    108
Kings XI Punjab                101
Sunrisers Hyderabad             97
Delhi Daredevils                77
Delhi Capitals                  50
Deccan Chargers                 36
Punjab Kings                    26
Gujarat Titans                  24
Pune Warriors                   23
Lucknow Super Giants            21
Gujarat Lions                   14
Rising Pune Supergiant           9
Rising Pune Supergiants          8
Kochi Tuskers Kerala             7
Royal Challengers Bengaluru      6
Name: count, dtype: int64

--- TOSS_WINNER ---
toss_winner
Mumbai Indians                 144
Kolkata Knight Riders          124
Chennai Super Kings            123
Rajasthan Royals               122
Royal Challengers Bangalore    117
Sunrisers Hyderabad             89
Kings XI Punjab                 87
Delhi Daredevils                80
Delhi Capitals                  50
Deccan Chargers                 44
Punjab Kings                    25
Gujarat Titans                  22
Pune Warriors                   20
Lucknow Super Giants            19
Gujarat Lions                   16
Kochi Tuskers Kerala             8
Royal Challengers Bengaluru      8
Rising Pune Supergiants          7
Rising Pune Supergiant           6
Name: count, dtype: int64

--- TOSS_DECISION ---
toss_decision
field    717
bat      394
Name: count, dtype: int64

--- WINNER ---
winner
Mumbai Indians                 145
Chennai Super Kings            138
Kolkata Knight Riders          135
Royal Challengers Bangalore    118
Rajasthan Royals               114
Kings XI Punjab                 90
Sunrisers Hyderabad             89
Delhi Daredevils                69
Delhi Capitals                  48
Deccan Chargers                 29
Gujarat Titans                  28
Punjab Kings                    26
Lucknow Super Giants            24
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Royal Challengers Bengaluru      7
Kochi Tuskers Kerala             6
NaN                              5
Rising Pune Supergiants          5
Name: count, dtype: int64